/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emaildownloader;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author nicho
 */
public class EmailExtractorGUI extends javax.swing.JDialog {

    /**
     * Creates new form EmailExtractorGUI
     */
    private Settings settings;
    private int emailNumber;
    
    public EmailExtractorGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.settings= new Settings();
        //unsubList
        settings.SaveSetting("string", "unsubList", "");
        settings.SaveSetting("string", "comListEx", "");
        settings.SaveSetting("string", "sentList", "");
        settings.SaveSetting("string", "destFoldEx", "");
        this.labelUnsubList.setForeground(Color.red);
        this.labelUnsubList.setText("EMPTY");
        this.labelComList.setForeground(Color.red);
        this.labelComList.setText("EMPTY");
        this.labelSentList.setForeground(Color.red);
        this.labelSentList.setText("EMPTY");
        this.labelDestList.setForeground(Color.red);
        this.labelDestList.setText("EMPTY");
        this.emailNumber= 0;
        this.txtCity.setText("");
        this.txtGroup.setText("");
    }
    
    private boolean checkSettings(){
        if(settings.getStringValue("comListEx").length()<3){
            JOptionPane.showMessageDialog(null, "Add Complete List");
            return false;
        }
        if(settings.getStringValue("unsubList").length()<3 && settings.getStringValue("sentList").length()<3){
            JOptionPane.showMessageDialog(null, "WARNING Unsub and Sent List Empty");
        }
        if(settings.getStringValue("destFoldEx").length()<3){
            JOptionPane.showMessageDialog(null, "Add Dest Folder");
            return false;
        }
        String tmpTxtEmail= this.txtEmail.getText();
        if(tmpTxtEmail.length()==0){
            JOptionPane.showMessageDialog(null, "Add Email Limit");
            this.txtEmail.setText("");
            return false;
        }else{
            try{
            Integer.valueOf(tmpTxtEmail);
            this.emailNumber= Integer.valueOf(tmpTxtEmail);
            if(this.emailNumber==0){
                JOptionPane.showMessageDialog(null, "Number Must be >=1");
                this.txtEmail.setText("");
                return false;
            }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Invalid input, integer required");
                this.emailNumber=0;
                this.txtEmail.setText("");
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelComList6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnComList = new javax.swing.JButton();
        labelComList = new javax.swing.JLabel();
        btnUnsubList = new javax.swing.JButton();
        labelUnsubList = new javax.swing.JLabel();
        labelComList2 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        labelComList3 = new javax.swing.JLabel();
        txtGroup = new javax.swing.JTextField();
        labelComList4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSentList = new javax.swing.JButton();
        labelSentList = new javax.swing.JLabel();
        btnDestList = new javax.swing.JButton();
        labelDestList = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        txtCountFixed = new javax.swing.JLabel();
        txtCounter = new javax.swing.JLabel();

        labelComList6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelComList6.setText("Count");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Email Extractor");

        btnComList.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnComList.setText("Complete List");
        btnComList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComListActionPerformed(evt);
            }
        });

        labelComList.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelComList.setText("EMPTY");

        btnUnsubList.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnUnsubList.setText("Unsub MailChimp");
        btnUnsubList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnsubListActionPerformed(evt);
            }
        });

        labelUnsubList.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelUnsubList.setText("EMPTY");

        labelComList2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelComList2.setText("City");

        labelComList3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelComList3.setText("Group");

        labelComList4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelComList4.setText("Email Number");

        btnSentList.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnSentList.setText("Sent MailChimp");
        btnSentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSentListActionPerformed(evt);
            }
        });

        labelSentList.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelSentList.setText("EMPTY");

        btnDestList.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnDestList.setText("Destination");
        btnDestList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestListActionPerformed(evt);
            }
        });

        labelDestList.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelDestList.setText("EMPTY");

        btnStart.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(0, 204, 0));
        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        txtCountFixed.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        txtCountFixed.setText("Count");

        txtCounter.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        txtCounter.setText("0000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDestList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSentList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUnsubList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnComList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(labelComList))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(labelUnsubList)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(labelSentList)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(labelDestList)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelComList2)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelComList3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelComList4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCountFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCounter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStart)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComList)
                            .addComponent(labelComList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUnsubList)
                            .addComponent(labelUnsubList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSentList)
                            .addComponent(labelSentList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDestList)
                            .addComponent(labelDestList)
                            .addComponent(txtCountFixed)
                            .addComponent(txtCounter)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelComList2)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelComList3)
                            .addComponent(txtGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelComList4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStart)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComListActionPerformed
        FolderSelect fs= new FolderSelect(null, true, "comListEx");
        fs.setVisible(true);
        if(settings.getStringValue("comListEx").length()<3){
            this.labelComList.setForeground(Color.red);
            this.labelComList.setText("EMPTY");
            JOptionPane.showMessageDialog(null, "Add Complete List");
        }
        else{
            this.labelComList.setForeground(Color.blue);
            this.labelComList.setText("OK");
        }
    }//GEN-LAST:event_btnComListActionPerformed

    private void btnUnsubListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnsubListActionPerformed
        FolderSelect fs= new FolderSelect(null, true, "unsubList");
        fs.setVisible(true);
        if(settings.getStringValue("unsubList").length()<3){
            this.labelUnsubList.setForeground(Color.red);
            this.labelUnsubList.setText("EMPTY");
            JOptionPane.showMessageDialog(null, "Add Unsub List");
        }
        else{
            this.labelUnsubList.setForeground(Color.blue);
            this.labelUnsubList.setText("OK");
        }
    }//GEN-LAST:event_btnUnsubListActionPerformed

    private void btnSentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSentListActionPerformed
        FolderSelect fs= new FolderSelect(null, true, "sentList");
        fs.setVisible(true);
        if(settings.getStringValue("sentList").length()<3){
            this.labelSentList.setForeground(Color.red);
            this.labelSentList.setText("EMPTY");
            JOptionPane.showMessageDialog(null, "Add Sent List");
        }
        else{
            this.labelSentList.setForeground(Color.blue);
            this.labelSentList.setText("OK");
        }
    }//GEN-LAST:event_btnSentListActionPerformed

    private void btnDestListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestListActionPerformed
        FolderSelect fs= new FolderSelect(null, true, "destFoldEx");
        fs.setVisible(true);
        if(settings.getStringValue("destFoldEx").length()<3){
            this.labelDestList.setForeground(Color.red);
            this.labelDestList.setText("EMPTY");
            JOptionPane.showMessageDialog(null, "Add Dest Folder");
        }
        else{
            this.labelDestList.setForeground(Color.blue);
            this.labelDestList.setText("OK");
        }
    }//GEN-LAST:event_btnDestListActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if(checkSettings()){
            EmailExtractor ee= new EmailExtractor(settings.getStringValue("comListEx"), settings.getStringValue("unsubList"), settings.getStringValue("sentList"), settings.getStringValue("destFoldEx"), this.emailNumber, this.txtCounter, this.txtCity.getText().toLowerCase(), this.txtGroup.getText().toLowerCase());
            Thread thrEe= new Thread(ee);
            thrEe.start();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailExtractorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailExtractorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailExtractorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailExtractorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmailExtractorGUI dialog = new EmailExtractorGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComList;
    private javax.swing.JButton btnDestList;
    private javax.swing.JButton btnSentList;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnUnsubList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelComList;
    private javax.swing.JLabel labelComList2;
    private javax.swing.JLabel labelComList3;
    private javax.swing.JLabel labelComList4;
    private javax.swing.JLabel labelComList6;
    private javax.swing.JLabel labelDestList;
    private javax.swing.JLabel labelSentList;
    private javax.swing.JLabel labelUnsubList;
    private javax.swing.JTextField txtCity;
    private javax.swing.JLabel txtCountFixed;
    private javax.swing.JLabel txtCounter;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGroup;
    // End of variables declaration//GEN-END:variables
}
